
export const icons = {
    raspberry: "https://img.icons8.com/fluency/512/raspberry.png",
    tomato: "https://img.icons8.com/fluency/512/tomato.png",
    carrot: "https://img.icons8.com/fluency/512/carrot.png",
    broccoli: "https://img.icons8.com/fluency/512/broccoli.png",
    onion: "https://img.icons8.com/fluency/512/onion.png",
    garlic: "https://img.icons8.com/fluency/512/garlic.png",
    potato: "https://img.icons8.com/fluency/512/potato.png",
    cucumber: "https://img.icons8.com/fluency/512/cucumber.png",
    pepper: "https://img.icons8.com/fluency/512/pepper.png",
    eggplant: "https://img.icons8.com/fluency/512/eggplant.png",
    pumpkin: "https://img.icons8.com/fluency/512/pumpkin.png",
    milk: "https://img.icons8.com/fluency/512/milk.png",
    cheese: "https://img.icons8.com/fluency/512/cheese.png",
    timer: "https://img.icons8.com/fluency/512/timer.png",
    leftArrow: "https://img.icons8.com/ios/512/long-arrow-left.png",
    share: "https://img.icons8.com/ios/512/share.png",
    pasta: "https://img.icons8.com/fluency/512/spaghetti.png",
    bacon: "https://img.icons8.com/fluency/512/bacon.png",
    egg: "https://img.icons8.com/fluency/512/sunny-side-up-eggs.png",
    chicken: "https://img.icons8.com/fluency/512/chicken.png",
    beef: "https://img.icons8.com/fluency/512/beef.png",
    play: require('../../assets/icon/play.png'),
    pause: require('../../assets/icon/pause.png'),
    stop: require('../../assets/icon/stop.png'),
    change: require('../../assets/icon/change.png'),
    salmon: "https://img.icons8.com/fluency/512/fish.png",
    avocado: "https://img.icons8.com/fluency/512/avocado.png",
    lemon: "https://img.icons8.com/fluency/512/citrus.png",
    salt: "https://img.icons8.com/fluency/512/salt-shaker.png",
    oliveOil: "https://img.icons8.com/fluency/512/olive-oil.png",
    strawberry: "https://img.icons8.com/fluency/512/strawberry.png",
    sugar: "https://img.icons8.com/fluency/512/sugar-cubes.png",
    water: "https://img.icons8.com/fluency/512/water.png",
    ice: "https://img.icons8.com/fluency/512/snowflake.png",
    basil: "https://img.icons8.com/fluency/512/basil.png",
    pineNut: "https://img.icons8.com/fluency/512/nut.png",
    soySauce: "https://img.icons8.com/fluency/512/soy-sauce.png",
    ginger: "https://img.icons8.com/fluency/512/ginger.png",
    steak: "https://img.icons8.com/fluencys/512/steak.png",
    chili: "https://img.icons8.com/fluency/512/chili-pepper.png",
    paprika: "https://img.icons8.com/fluency/512/paprika.png",
    lettuce: "https://img.icons8.com/fluency/512/lettuce.png",
    flour: "https://img.icons8.com/fluency/512/flour.png",
    curry: "https://img.icons8.com/fluency/512/curry.png",
    rice: "https://img.icons8.com/fluency/512/rice-bowl.png",
    banana: "https://img.icons8.com/fluency/512/banana.png",
    yogurt: "https://img.icons8.com/fluency/512/yogurt.png",
    mango: "https://img.icons8.com/fluency/512/mango.png",
    watermelon: "https://img.icons8.com/fluency/512/watermelon.png",
    mint: "https://img.icons8.com/fluency/512/leaf.png",
    lime: "https://img.icons8.com/fluency/512/lime.png",





}